---
- name: Wait for DB port to be available
  wait_for:
    port: '{{ daybyday_crm_db_cont_port }}'
    delay: 5

- name: Run database migrations
  command: |
    docker exec {{ daybyday_crm_app_cont_name }} \
      php artisan migrate --force --no-interaction

- name: Check if database needs seeding
  command: |
    docker exec {{ daybyday_crm_db_cont_name }} \
      mysql -p --password=changeIfYouCare daybydaycrm \
      -e 'SELECT name FROM users;'
  register: users_query

- name: Seed database with data
  when: daybyday_crm_admin_user_name not in users_query.stdout
  command: |
    docker exec {{ daybyday_crm_app_cont_name }} \
      php artisan db:seed --force --no-interaction

- name: Update administrator user
  command: |
    docker exec {{ daybyday_crm_app_cont_name }} \
      php artisan tinker --execute="
        User::where('id',1)->update(array(
          'name'=>'{{ daybyday_crm_admin_user_name | mandatory }}',
          'email'=>'{{ daybyday_crm_admin_user_email | mandatory }}',
          'password'=>Hash::make('{{ daybyday_crm_admin_user_pass | mandatory }}')
        ));
      "
