---
- name: Wait for DB port to be available
  wait_for:
    port: '{{ daybyday_crm_db_cont_port }}'
    delay: 5

- name: Run database migrations
  command: |
    docker exec {{ daybyday_crm_app_cont_name }} \
      php artisan migrate --seed

#- name: Delete seeded admin user
#  command: |
#    docker exec {{ daybyday_crm_app_cont_name }} \
#      php artisan tinker --execute="
#        DB::table('users')->delete(['id'=>1]);

- name: Create administrator user
  command: |
    docker exec {{ daybyday_crm_app_cont_name }} \
      php artisan tinker --execute="
        DB::table('users')->insert([
          'name'=>'{{ daybyday_crm_admin_user_name | mandatory }}',
          'email'=>'{{ daybyday_crm_admin_user_email | mandatory }}',
          'password'=>Hash::make('{{ daybyday_crm_admin_user_pass | mandatory }}')
        ]);
      "
