---
- name: Create directory for DB data
  file:
    path: '{{ item }}'
    owner: '{{ daybyday_crm_db_host_uid }}'
    group: dockremap
    state: directory
    recurse: true
  with_items:
    - '{{ daybyday_crm_db_cont_vol }}/data'
    - '{{ daybyday_crm_db_cont_vol }}/backup'

- name: Create directory for ES data
  file:
    path: '{{ daybyday_crm_es_cont_vol }}'
    owner: '{{ daybyday_crm_es_host_uid }}'
    group: dockremap
    state: directory
    recurse: true

- name: Create environment file
  template:
    src: 'app.env.j2'
    dest: '{{ daybyday_crm_service_path }}/app.env'
    owner: 'dockremap'
    group: 'docker'

- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ daybyday_crm_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  docker_compose:
    project_src: '{{ daybyday_crm_service_path }}'
    pull: true
    build: false
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate | default("smart") }}'
