---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul encryption key
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul", field="encryption-key")}}'

# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "CloudFlare/status.im", file="origin.key")}}'
    default: true

# Master password for backups
restic_repo_master_pass: '{{lookup("bitwarden", "restic-backups/repo", field="master-pass")}}'
restic_ssh_public_key: '{{lookup("bitwarden", "restic-backups/ssh", field="public")}}'
