---
swap_file_size_mb: 2048

# DayByDay-CRM
daybyday_crm_domain: 'admin-ambassador.status.im'
# Admin
daybyday_crm_admin_user_name: 'admin'
daybyday_crm_admin_user_pass: '{{lookup("bitwarden", "daybydaycrm/admin")}}'
daybyday_crm_admin_user_email: 'devops@status.im'
# Ports
daybyday_crm_proxy_cont_port: 9080

# Open Nginx Ports
open_ports_default_comment: 'Nginx'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: 80  }
  - { port: 443 }

# Nginx SSL Proxy configuration
nginx_sites:
  crm_http:
    - listen 80
    - server_name {{ daybyday_crm_domain | mandatory }}
    - return 301 https://$host$request_uri

  crm_ssl:
    - listen 443 ssl
    - server_name {{ daybyday_crm_domain | mandatory }}

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - location / {
        proxy_pass http://127.0.0.1:{{ daybyday_crm_proxy_cont_port }}/;
        include /etc/nginx/proxy_params;
      }
