---
# SourceCred uses a lot of RAM
swap_file_size_mb: 2048

# Keycloak Auth
keycloak_domain: 'keycloak.status.im'
keycloak_admin_username: 'admin'
keycloak_admin_password: '{{ lookup("passwordstore", "services/keycloak/admin-pass") }}'
keycloak_app_cont_public_port: 8080

# Open Nginx Ports
open_ports_default_comment: 'Keycloak'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: 80  }
  - { port: 443 }

# Nginx SSL Proxy configuration
nginx_sites:
  keycloak_http:
    - listen 80
    - server_name {{ keycloak_domain | mandatory }}
    - return 301 https://$host$request_uri

  keycloak_ssl:
    - listen 443 ssl
    - server_name {{ keycloak_domain | mandatory }}

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - location / {
        proxy_pass http://127.0.0.1:{{ keycloak_app_cont_public_port }}/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
      }
