---
# SourceCred uses a lot of RAM
swap_file_size_mb: 2048

# Keycloak Auth
keycloak_domain: 'auth.status.im'
keycloak_admin_domain: 'keycloak.infra.status.im'
keycloak_admin_username: 'admin'
keycloak_admin_password: '{{ lookup("passwordstore", "services/keycloak/admin-pass") }}'
keycloak_app_cont_public_port: 8080

# Restic Backups
restic_user_groups: ['docker', 'dockremap']
restic_backups:
  - name: 'keycloak-db'
    tags: ['pgdumpdir']
    path: '/docker/keycloak/db/backup'
    after: 'dump-keycloak-db.service'
    frequency: 'daily'
    timeout: 300

# Open Nginx Ports
open_ports_default_comment: 'Keycloak'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: 80  }
  - { port: 443 }

# Nginx SSL Proxy configuration
nginx_sites:
  keycloak_http:
    - listen 80
    - server_name {{ keycloak_domain }} {{ keycloak_admin_domain }}
    - return 301 https://$host$request_uri

  keycloak_ssl:
    - listen 443 ssl
    - server_name {{ keycloak_domain }}

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - location / {
        proxy_pass http://127.0.0.1:{{ keycloak_app_cont_public_port }}/;
        proxy_set_header X-Forwarded-Host $http_host;
        include /etc/nginx/proxy_params;
      }

  keycloak_admin:
    - listen 443 ssl
    - server_name {{ keycloak_admin_domain }}

    - ssl_certificate     /certs/origin.crt
    - ssl_certificate_key /certs/origin.key

    - location = / {
        return 302 /admin;
      }

    - location / {
        proxy_pass http://127.0.0.1:{{ keycloak_app_cont_public_port }}/;
        proxy_set_header X-Forwarded-Host $http_host;
        include /etc/nginx/proxy_params;
      }
