---
# Wekan
wekan_domain: 'boards.status.im'
wekan_app_cont_port: 8280
wekan_smtp_port: 587
wekan_smtp_host: 'smtp.mailgun.org'
wekan_smtp_user: '{{lookup("bitwarden", "MailGun", field="smtp-user")}}'
wekan_smtp_pass: '{{lookup("bitwarden", "MailGun", field="smtp-pass")}}'
wekan_smtp_from: 'Status.im Wekan Boards <wekan@mgun.status.im>'

# Restic Backups
restic_user_groups: ['dockremap', 'docker']
restic_backups:
  - name: 'wekan-db'
    tags: ['mongodump']
    path: '/docker/wekan/db/backup'
    after: 'dump-wekan-db.service'
    frequency: 'daily'
    timeout: 120

# Open Nginx Ports
open_ports_default_comment: 'Wekan'
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: '{{ wekan_app_cont_port }}', ipset: 'proxy.misc' }
