---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ wekan_app_cont_name }}'
    consul_services:
      - name: '{{ wekan_app_cont_name }}'
        tags: ['wekan', 'misc']
        # we advertise the port with basic auth
        port: '{{ wekan_app_cont_port }}'
        checks:
          - id: wekan-status
            name: Wekan Healthcheck
            type: http
            http: 'http://localhost:{{ wekan_app_cont_port }}/api/user'
