---
- name: Create DB directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ wekan_db_host_uid }}'
    group: 'dockremap'
    recurse: true
  with_items:
    - '{{ wekan_db_cont_vol }}/data'
    - '{{ wekan_db_cont_vol }}/backup'

- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ wekan_compose_file }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

- name: Create containers
  docker_compose:
    project_src: '{{ wekan_service_path }}'
    pull: true
    build: false
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate | default("smart") }}'
