---
- name: Create directory for DB data
  file:
    path: '{{ item }}'
    state: directory
    owner: 'dockremap'
    recurse: true
  with_items:
    - '{{ wekan_db_cont_vol }}/data'
    - '{{ wekan_db_cont_vol }}/backup'

- name: Start MongoDB container
  docker_container:
    name: '{{ wekan_db_cont_name }}'
    image: '{{ wekan_db_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    entrypoint: mongod 
    command: |
      --smallfiles
      --oplogSize=128
    ports:
      - '{{ wekan_db_cont_port }}:{{ wekan_db_cont_port }}'
    volumes:
      - '{{ wekan_db_cont_vol }}/data:/data/db'
      - '{{ wekan_db_cont_vol }}/backup:/backup'
