---
- name: Configure nginx proxy for Wekan
  include_role:
    name: nginx
  vars:
    nginx_sites:
      wekan:
        - listen 443 ssl
    
        - server_name {{ wekan_domain }}
    
        - ssl_certificate     /certs/origin.crt
        - ssl_certificate_key /certs/origin.key
    
        - proxy_set_header X-Frame-Options sameorigin

        - location / {
            proxy_pass http://localhost:{{ wekan_cont_port }}/;
          }
