---
- name: Configure Nginx proxy
  include_role:
    name: nginx
  vars:
    nginx_sites:
      wekan_http:
        - listen 80
        - server_name {{ wekan_domain | mandatory }}
        - return 301 https://$host$request_uri

      wekan_ssl:
        - listen 443 ssl
        - server_name {{ wekan_domain }}
    
        - ssl_certificate     /certs/origin.crt
        - ssl_certificate_key /certs/origin.key
    
        - proxy_set_header X-Frame-Options sameorigin

        - location / {
            proxy_pass http://localhost:{{ wekan_app_cont_port }}/;
          }
