---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Gitea host
  hosts: gitea
  roles:
    - { role: infra-role-swap-file,      tags: swap-file }
    - { role: infra-role-open-ports,     tags: open-ports }
    - { role: infra-role-origin-certs,   tags: origin-certs }
    - { role: infra-role-gitea,          tags: gitea }
    - { role: infra-role-gitea-mirrors,  tags: gitea-mirrors }
    - { role: infra-role-restic-backups, tags: restic-backups }
    - { role: infra-role-nginx,          tags: nginx }
    - { role: infra-role-threatstack,    tags: threatstack }
