---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: f7dcb7e1944d2ec0655bf8e7ce6f45a1317b65b9
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: b1b60917e839f9205af3952574b1f2c893aaedba
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 7b63fb7b5f0c525aa191e1a410fd79f7eab8d11a
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: fbcc0ce58776c59cf6e0ff9b7d605663ac3e7b95
  scm: git

- name: restic-backups
  src: git@github.com:status-im/infra-role-restic-backups.git
  version: b0debe383d45eac9e280dc3a143957b05fdc0c73
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: a5ab4b97d0ccdaed3489dba535624f85ab484f9f
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: c0c96298270c1763e819967ff1cad4ad876506b0
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 241dffb0f865f8558b5e373d20fefed0a08a21ef
  scm: git

- name: threatstack
  src: git@github.com:status-im/infra-role-threatstack.git
  version: 552e60c1ab862ac8c73d4c9cba58e7f6f2261fdd
  scm: git
