---
- name: 'Verify Ansible versions'
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Octobox, HackMD
  hosts: todo
  roles:
    - { role: infra-role-swap-file,      tags: swap-file }
    - { role: infra-role-open-ports,     tags: open-ports }
    - { role: infra-role-origin-certs,   tags: origin-certs }
    - { role: infra-role-codimd,         tags: codimd }
    - { role: infra-role-octobox,        tags: octobox }
    - { role: infra-role-nginx,          tags: nginx }
    - { role: infra-role-nginx-metrics,  tags: nginx-metrics }
    - { role: infra-role-restic-backups, tags: restic-backups }
    - { role: infra-role-threatstack,    tags: threatstack }
