---
- name: 'Verify Ansible versions'
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure Wekan, Octobox, HackMD
  hosts: todo
  roles:
    - { role: swap-file,          tags: swap-file }
    - { role: open-ports,         tags: open-ports }
    - { role: origin-certs,       tags: origin-certs }
    - { role: hackmd,             tags: hackmd }
    - { role: wekan,              tags: wekan }
    - { role: octobox,            tags: octobox }
    - { role: shlink,             tags: shlink }
    - { role: nginx,              tags: nginx }
    - { role: restic-backups,     tags: restic-backups }
    - { role: threatstack,        tags: threatstack }
