---
- name: 'Verify Ansible versions'
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Wekan kanban board
  hosts: wekan
  roles:
    - { role: infra-role-swap-file,      tags: swap-file      }
    - { role: infra-role-open-ports,     tags: open-ports     }
    - { role: wekan,                     tags: wekan          }
    - { role: infra-role-restic-backups, tags: restic-backups }
